# 生产环境Cloudflare Worker配置
name = "tldraw-production"
main = "worker/worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 生产环境变量
[env.production]
name = "tldraw-production"

[env.production.vars]
ENVIRONMENT = "production"
# 这些值应该通过 wrangler secret 命令设置，而不是写在配置文件中
# CLERK_SECRET_KEY = "设置为实际的Clerk密钥"
# ADMIN_TOKEN = "设置为强密码"

# D1数据库绑定
[[env.production.d1_databases]]
binding = "ROOM_DB"
database_name = "tldraw-rooms-prod"
database_id = "生产环境数据库ID"

# Durable Object绑定
[[env.production.durable_objects.bindings]]
name = "TLDRAW_DURABLE_OBJECT"
class_name = "TldrawDurableObject"

# R2存储绑定（用于文件上传）
[[env.production.r2_buckets]]
binding = "TLDRAW_BUCKET"
bucket_name = "tldraw-assets-prod"

# 静态资源绑定
[[env.production.assets]]
binding = "ASSETS"

# 速率限制（防止滥用）
[env.production.limits]
cpu_ms = 50
memory_mb = 128

# 开发环境配置
[env.development]
name = "tldraw-dev"

[env.development.vars]
ENVIRONMENT = "development"
ADMIN_TOKEN = "dev-admin-123"

[[env.development.d1_databases]]
binding = "ROOM_DB"
database_name = "tldraw-rooms-dev"
database_id = "开发环境数据库ID"

[[env.development.durable_objects.bindings]]
name = "TLDRAW_DURABLE_OBJECT"
class_name = "TldrawDurableObject"

[[env.development.r2_buckets]]
binding = "TLDRAW_BUCKET"
bucket_name = "tldraw-assets-dev"

[[env.development.assets]]
binding = "ASSETS"